global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['13.235.94.83:9100']
  - job_name: 'wordpress'
    metrics_path: /
    scheme: http
    static_configs:
      - targets: ['13.235.94.83:80']
  - job_name: 'wordpress-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    scheme: http
    static_configs:
      - targets: ['13.235.94.83:80']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 13.235.94.83:9115
